stages:
  always_run:
    # when you don't specify deps, it will always run when : dvc repro
    # This helps mostly when you want to do a cleanup: you create a cleanup file that
    # should always run first. 
    cmd: python rough/test.py
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/winequality-red.csv
    
  split_data:
    cmd: python src/stage_02_split_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts/split_data_dir/test.csv
      - artifacts/split_data_dir/train.csv
    